query GetUser($id: uuid!) {
  auth_user_by_pk(id: $id) {
    id
    stripe_customer_id
    subscribtion_plan
    stripe_subscribtion_id
    team_id
  }
}

query GetUserEmail($id: uuid!) {
  auth_user_by_pk(id: $id) {
    email
  }
}

mutation UpdateUsername($id: uuid!, $username: String!) {
  update_auth_user_by_pk(
    pk_columns: { id: $id }
    _set: { username: $username }
  ) {
    username
  }
}

mutation UpdateEmail($id: uuid!, $email: String!) {
  update_auth_user_by_pk(pk_columns: { id: $id }, _set: { email: $email }) {
    email
  }
}

mutation UpdateUpdatedEmail($id: uuid!, $updated_email: String!) {
  update_auth_user_by_pk(
    pk_columns: { id: $id }
    _set: { updated_email: $updated_email }
  ) {
    updated_email
  }
}

query GetSubscriptionPlans($languageCode: String!) {
  subscribtion_plan {
    name
    stripe_monthly_price_id
    stripe_yearly_price_id
    popular
    text_content {
      translations(where: { language: { _eq: $languageCode } }) {
        text_label
        translation
      }
    }
    subscribtion_plan_subscribtion_feature_assocs {
      subscribtionFeatureBySubscribtionFeature {
        text_content {
          translations(where: { language: { _eq: $languageCode } }) {
            translation
          }
        }
      }
    }
  }
}

query GetSubscriptionPlanNameByPriceId(
  $id: String! = "price_1Phb7pBeHVeQHE2CEo8SjlIg"
) {
  subscribtion_plan(
    where: {
      _or: [
        { stripe_monthly_price_id: { _eq: $id } }
        { stripe_yearly_price_id: { _eq: $id } }
      ]
    }
  ) {
    name
  }
}

mutation UpdateUserSubscriptionPlan(
  $id: uuid!
  $stripe_customer_id: String!
  $subscribtion_plan: String!
  $subscribtion_id: String!
) {
  update_auth_user_by_pk(
    pk_columns: { id: $id }
    _set: {
      stripe_customer_id: $stripe_customer_id
      subscribtion_plan: $subscribtion_plan
      stripe_subscribtion_id: $subscribtion_id
    }
  ) {
    id
  }
}

mutation CreateTeam($name: String!) {
  insert_team_one(object: { name: $name }) {
    id
    name
  }
}

mutation UpdateUserTeamId($id: uuid!, $teamid: uuid!) {
  update_auth_user_by_pk(pk_columns: { id: $id }, _set: { team_id: $teamid }) {
    id
  }
}

query GetUserTeamName($teamid: uuid!) {
  team_by_pk(id: $teamid) {
    name
  }
}

mutation UpdateUnsubscriptionFeedback($feedback: String!) {
  insert_unsubscription_feedback_one(object: { feedback: $feedback }) {
    id
  }
}

query GetSubsciptionPlanTranslationByNameAndLng(
  $name: String!
  $language: String!
) {
  subscribtion_plan(where: { name: { _eq: $name } }) {
    text_content {
      translations(
        where: { language: { _eq: $language }, text_label: { _eq: "name" } }
      ) {
        translation
      }
    }
  }
}
